-- Migración para poblar las keywords de categorización

-- Insertar keywords para categorización automática
INSERT INTO public.category_keywords (keyword, category_id, priority) VALUES
-- Verduras y Frutas
('manzana', 'vegetables', 10),
('banana', 'vegetables', 10),
('naranja', 'vegetables', 10),
('pera', 'vegetables', 10),
('uva', 'vegetables', 10),
('limon', 'vegetables', 10),
('limón', 'vegetables', 10),
('kiwi', 'vegetables', 10),
('mango', 'vegetables', 10),
('piña', 'vegetables', 10),
('sandia', 'vegetables', 10),
('melon', 'vegetables', 10),
('frutilla', 'vegetables', 10),
('fresa', 'vegetables', 10),
('cereza', 'vegetables', 10),
('durazno', 'vegetables', 10),
('ciruela', 'vegetables', 10),
('palta', 'vegetables', 10),
('aguacate', 'vegetables', 10),
('tomate', 'vegetables', 9),
('cebolla', 'vegetables', 9),
('ajo', 'vegetables', 9),
('papa', 'vegetables', 9),
('zanahoria', 'vegetables', 9),
('lechuga', 'vegetables', 9),
('espinaca', 'vegetables', 9),
('acelga', 'vegetables', 9),
('repollo', 'vegetables', 9),
('coliflor', 'vegetables', 9),
('brocoli', 'vegetables', 9),
('brócoli', 'vegetables', 9),
('zapallo', 'vegetables', 9),
('calabaza', 'vegetables', 9),
('berenjena', 'vegetables', 9),
('pepino', 'vegetables', 9),
('pimiento', 'vegetables', 9),
('morron', 'vegetables', 9),
('pimenton', 'vegetables', 9),
('choclo', 'vegetables', 9),
('maiz', 'vegetables', 9),
('maíz', 'vegetables', 9),
('arveja', 'vegetables', 9),
('arvejas', 'vegetables', 9),
('chaucha', 'vegetables', 9),
('judia', 'vegetables', 9),
('habas', 'vegetables', 9),
('rabanito', 'vegetables', 9),
('remolacha', 'vegetables', 9),
('apio', 'vegetables', 9),
('perejil', 'vegetables', 9),
('cilantro', 'vegetables', 9),
('albahaca', 'vegetables', 9),
('menta', 'vegetables', 9),

-- Lácteos y Huevos
('leche', 'dairy', 10),
('yogur', 'dairy', 10),
('yogurt', 'dairy', 10),
('queso', 'dairy', 10),
('mantequilla', 'dairy', 10),
('crema', 'dairy', 10),
('huevo', 'dairy', 10),
('huevos', 'dairy', 10),
('yogurt', 'dairy', 10),
('ricota', 'dairy', 10),
('muzzarella', 'dairy', 10),
('mozzarella', 'dairy', 10),
('parmesano', 'dairy', 10),
('roquefort', 'dairy', 10),
('gorgonzola', 'dairy', 10),
('cheddar', 'dairy', 10),
('provolone', 'dairy', 10),
('feta', 'dairy', 10),
('cuajada', 'dairy', 10),
('requeson', 'dairy', 10),
('nata', 'dairy', 10),
('leche condensada', 'dairy', 9),
('dulce de leche', 'dairy', 9),

-- Carnes y Pescados
('pollo', 'meat', 10),
('carne', 'meat', 10),
('vaca', 'meat', 10),
('res', 'meat', 10),
('cerdo', 'meat', 10),
('chancho', 'meat', 10),
('cordero', 'meat', 10),
('pavo', 'meat', 10),
('conejo', 'meat', 10),
('higado', 'meat', 10),
('hígado', 'meat', 10),
('molleja', 'meat', 10),
('corazon', 'meat', 10),
('corazón', 'meat', 10),
('riñon', 'meat', 10),
('riñón', 'meat', 10),
('pescado', 'meat', 10),
('salmón', 'meat', 10),
('merluza', 'meat', 10),
('atun', 'meat', 10),
('atún', 'meat', 10),
('sardina', 'meat', 10),
('caballa', 'meat', 10),
('trucha', 'meat', 10),
('bacalao', 'meat', 10),
('calamar', 'meat', 10),
('camarón', 'meat', 10),
('langosta', 'meat', 10),
('mejillón', 'meat', 10),
('mejillon', 'meat', 10),
('almeja', 'meat', 10),
('chorizo', 'meat', 9),
('salchicha', 'meat', 9),
('mortadela', 'meat', 9),
('jamon', 'meat', 9),
('jamón', 'meat', 9),
('bondiola', 'meat', 9),
('matambre', 'meat', 9),

-- Almacén
('arroz', 'pantry', 10),
('fideos', 'pantry', 10),
('pasta', 'pantry', 10),
('fideo', 'pantry', 10),
('harina', 'pantry', 10),
('azucar', 'pantry', 10),
('azúcar', 'pantry', 10),
('sal', 'pantry', 10),
('aceite', 'pantry', 10),
('vinagre', 'pantry', 10),
('mayonesa', 'pantry', 10),
('ketchup', 'pantry', 10),
('mostaza', 'pantry', 10),
('salsa', 'pantry', 10),
('pure de tomate', 'pantry', 9),
('pasta de tomate', 'pantry', 9),
('sopa', 'pantry', 9),
('caldo', 'pantry', 9),
('cereal', 'pantry', 9),
('avena', 'pantry', 9),
('galletas', 'pantry', 9),
('galletitas', 'pantry', 9),
('bizcochos', 'pantry', 9),
('pan', 'pantry', 9),
('pan lactal', 'pantry', 9),
('mermelada', 'pantry', 9),
('miel', 'pantry', 9),
('café', 'pantry', 9),
('cafe', 'pantry', 9),
('té', 'pantry', 9),
('te', 'pantry', 9),
('mate', 'pantry', 9),
('yerba', 'pantry', 9),
('polenta', 'pantry', 9),
('semola', 'pantry', 9),
('maicena', 'pantry', 9),
('levadura', 'pantry', 9),
('vainilla', 'pantry', 9),
('canela', 'pantry', 9),
('pimienta', 'pantry', 9),
('comino', 'pantry', 9),
('oregano', 'pantry', 9),
('laurel', 'pantry', 9),
('nuez moscada', 'pantry', 9),
('clavo de olor', 'pantry', 9),
('paprika', 'pantry', 9),
('curry', 'pantry', 9),

-- Bebidas
('agua', 'beverages', 10),
('jugo', 'beverages', 10),
('refresco', 'beverages', 10),
('gaseosa', 'beverages', 10),
('coca cola', 'beverages', 9),
('sprite', 'beverages', 9),
('fanta', 'beverages', 9),
('vino', 'beverages', 9),
('cerveza', 'beverages', 9),
('whisky', 'beverages', 9),
('vodka', 'beverages', 9),
('ron', 'beverages', 9),
('licor', 'beverages', 9),
('cafe', 'beverages', 9),
('café', 'beverages', 9),
('te', 'beverages', 9),
('té', 'beverages', 9),

-- Limpieza
('detergente', 'cleaning', 10),
('jabon', 'cleaning', 10),
('jabón', 'cleaning', 10),
('lavandina', 'cleaning', 10),
('cloro', 'cleaning', 10),
('desinfectante', 'cleaning', 10),
('limpiavidrios', 'cleaning', 9),
('lustrador', 'cleaning', 9),
('cera', 'cleaning', 9),
('shampoo', 'cleaning', 9),
('acondicionador', 'cleaning', 9),
('champu', 'cleaning', 9),

-- Congelados
('helado', 'frozen', 10),
('pizza', 'frozen', 10),
('hamburguesa', 'frozen', 10),
('papas fritas', 'frozen', 9),
('papas congeladas', 'frozen', 9),
('verduras congeladas', 'frozen', 9),
('frutas congeladas', 'frozen', 9),
('pescado congelado', 'frozen', 9),
('carne congelada', 'frozen', 9),

-- Cuidado Personal
('shampoo', 'personal_care', 10),
('acondicionador', 'personal_care', 10),
('jabon', 'personal_care', 10),
('jabón', 'personal_care', 10),
('pasta dental', 'personal_care', 10),
('cepillo de dientes', 'personal_care', 9),
('desodorante', 'personal_care', 9),
('crema', 'personal_care', 9),
('perfume', 'personal_care', 9),
('colonia', 'personal_care', 9)
ON CONFLICT (keyword) DO NOTHING;

-- Mensaje de confirmación
SELECT 'Keywords de categorización pobladas exitosamente - ' || COUNT(*) || ' keywords agregadas' FROM public.category_keywords;
